Feature/light mode
konrascher3/nf-capstone pull request #66
Opened 2022-02-19 01:59 UTC by konrascher3

## Motivation
Addedd a light-theme. 🌞

## Issues closed
* #65

2022-02-19 10:19 UTC, sedajune approved these changes
And let there be light! Finally. So many changed files, only one little detail to change and then let me merge this :P

2022-02-19 10:19 UTC, sedajune commented on src/molecules/please-login-component/PleaseLoginComponent.jsx
>  					Please login to access your watchlist!
Please log in to access your watchlist! (used as a verb in this case ;))

2022-02-19 16:00 UTC, doemser requested changes
Switching to darkmode and refreshing the browser, causes the header color to jump back to light-mode, while the rest ist persisting

2022-02-19 23:51 UTC, konrascher3 commented
Der color-mode persisted nicht mehr; nach einem page-reload setzt sich der color-mode auf dark zurück. Ist irgendwie ein Problem mit persist, deswegen habe ich den toggle da raus genommen. Das komische: im store steht der richtige Wert drinnen, aber der Wert wird nicht in der _app.jsx ausegelesen wenn er sich ändert. Hab es auch mit useEffect versucht, aber ohne Erfolg. Ich lass das erstmal so.

2022-02-20 02:43 UTC, doemser approved these changes
lgtm

2022-02-20 15:09 UTC, konrascher3 commented on src/organisms/header/index.jsx
>  								/>
Added to the refactoring-stage

2022-02-20 15:09 UTC, merged